locals {
  project_name = "pitstop"
}


# Networking Module
# Creates the Pitstop VPC with public and private subnets across
# two availability zones, an Internet Gateway for public access,
# and a NAT Gateway for outbound-only internet from private subnets.
module "networking" {
  source = "./modules/networking"

  project_name = local.project_name
  cidr         = "10.0.0.0/16"

  public_subnets = {
    "public-1" = { cidr = "10.0.1.0/24", az = "us-east-1a" }
    "public-2" = { cidr = "10.0.2.0/24", az = "us-east-1b" }
  }

  private_subnets = {
    "private-1" = { cidr = "10.0.11.0/24", az = "us-east-1a" }
    "private-2" = { cidr = "10.0.12.0/24", az = "us-east-1b" }
  }


}


# ------------------------------------------------------------
# Security Module
# Creates one security group per tier and chains them so each
# tier only accepts traffic from the tier in front of it:
# Internet -> ALB (80) -> Web (80) -> DB (5432)
# ------------------------------------------------------------
module "security" {
  source       = "./modules/security"
  project_name = local.project_name
  vpc_id       = module.networking.vpc_id

  security_groups = {
    alb = "Allow HTTP from the internet to the load balancer"
    web = "Allow HTTP from the ALB to web servers"
    db  = "Allow PostgreSQL from web servers to RDS"
  }

  ingress_rules = {
    "alb-http-in" = {
      security_group = "alb"
      description    = "HTTP from internet"
      ip_protocol    = "tcp"
      from_port      = 80
      to_port        = 80
      cidr_ipv4      = "0.0.0.0/0"
    }
    "web-http-in" = {
      security_group            = "web"
      description               = "HTTP from ALB only"
      ip_protocol               = "tcp"
      from_port                 = 80
      to_port                   = 80
      referenced_security_group = "alb"
    }
    "db-postgres-in" = {
      security_group            = "db"
      description               = "PostgreSQL from web servers only"
      ip_protocol               = "tcp"
      from_port                 = 5432
      to_port                   = 5432
      referenced_security_group = "web"
    }
  }

  egress_rules = {
    "alb-to-web" = {
      security_group            = "alb"
      description               = "HTTP to web servers"
      ip_protocol               = "tcp"
      from_port                 = 80
      to_port                   = 80
      referenced_security_group = "web"
    }
    "web-all-out" = {
      security_group = "web"
      description    = "All outbound (NAT for updates, RDS)"
      ip_protocol    = "-1"
      cidr_ipv4      = "0.0.0.0/0"
    }
  }


  # Stateless subnet-level firewall. Replies need explicit
  # ephemeral port rules (1024-65535).
  network_acls = {

    public = {
      subnet_ids = module.networking.public_subnet_ids
      ingress = [
        { rule_no = 100, protocol = "tcp", action = "allow", cidr_block = "0.0.0.0/0", from_port = 80, to_port = 80 },
        { rule_no = 110, protocol = "tcp", action = "allow", cidr_block = module.networking.vpc_cidr, from_port = 443, to_port = 443 },
        { rule_no = 120, protocol = "tcp", action = "allow", cidr_block = "0.0.0.0/0", from_port = 1024, to_port = 65535 },
      ]
      egress = [
        { rule_no = 100, protocol = "tcp", action = "allow", cidr_block = "0.0.0.0/0", from_port = 80, to_port = 80 },
        { rule_no = 110, protocol = "tcp", action = "allow", cidr_block = "0.0.0.0/0", from_port = 443, to_port = 443 },
        { rule_no = 120, protocol = "tcp", action = "allow", cidr_block = "0.0.0.0/0", from_port = 1024, to_port = 65535 },
      ]
    }


    private = {
      subnet_ids = module.networking.private_subnet_ids
      ingress = [
        { rule_no = 100, protocol = "-1", action = "allow", cidr_block = module.networking.vpc_cidr },
        { rule_no = 110, protocol = "tcp", action = "allow", cidr_block = "0.0.0.0/0", from_port = 1024, to_port = 65535 },
      ]
      egress = [
        { rule_no = 100, protocol = "-1", action = "allow", cidr_block = module.networking.vpc_cidr },
        { rule_no = 110, protocol = "tcp", action = "allow", cidr_block = "0.0.0.0/0", from_port = 80, to_port = 80 },
        { rule_no = 120, protocol = "tcp", action = "allow", cidr_block = "0.0.0.0/0", from_port = 443, to_port = 443 },
      ]
    }
  }
}


# ------------------------------------------------------
# Database Module
# PostgreSQL on RDS in the private subnets. Single-AZ, free tier.
# The master password is generated by RDS and stored in
# Secrets Manager (default aws/secretsmanager key).
# ------------------------------------------------------------
module "database" {
  source               = "./modules/database"
  project_name         = local.project_name
  subnet_ids           = module.networking.private_subnet_ids
  db_security_group_id = module.security.security_group_ids["db"]
}



# ------------------------------------------------------------
# Compute Module
# Builds the golden AMI (S3 + builder EC2), then the launch
# template, ALB, target group, and Auto Scaling Group.
# ------------------------------------------------------------
module "compute" {
  source                = "./modules/compute"
  project_name          = local.project_name
  app_path              = "${path.root}/app"
  schema_path           = "${path.root}/db/schema.sql"
  builder_subnet_id     = module.networking.private_subnet_ids[0]
  web_security_group_id = module.security.security_group_ids["web"]

  # Database connection details (from the database module's outputs)
  db_host       = module.database.db_endpoint
  db_port       = module.database.db_port
  db_name       = module.database.db_name
  db_secret_arn = module.database.db_secret_arn

  vpc_id                = module.networking.vpc_id
  public_subnet_ids     = module.networking.public_subnet_ids
  private_subnet_ids    = module.networking.private_subnet_ids
  alb_security_group_id = module.security.security_group_ids["alb"]

}